export const REQUESTING_FILES = 'REQUESTING_FILES';
export const RECEIVED_FILES = 'RECEIVED_FILES';
export const REQUESTING_FILES_ERROR = 'REQUESTING_FILES_ERROR';

export const RENAMING_FILE = 'RENAMING_FILE';
export const RENAMED_FILE = 'RENAMED_FILE';
export const RENAMING_FILE_ERROR = 'RENAMING_FILE_ERROR';

export const REQUESTING_TAGS = 'REQUESTING_TAGS';
export const RECEIVED_TAGS = 'RECEIVED_TAGS';
export const REQUESTING_TAGS_ERROR = 'REQUESTING_TAGS_ERROR';